# -*- coding: utf-8 -*-
"""Feature Scaling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X3gbY043b_BWy_hpqOJ3mnBUwY5bZz4c
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib as plt
import seaborn as sns
# %matplotlib inline

df=pd.read_csv('income.csv')
df.head()

data=df.drop(["capital_gain","capital_loss","income_level"], axis=1)
data.head()

sns.pairplot(data)

data.describe()



"""# Normalization"""

df=data

from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
df=scaler.fit_transform(df)

df= pd.DataFrame(df)

df.describe().round(2)

sns.pairplot(df)

"""# standarization"""

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
df2=scaler.fit_transform(data)

df2= pd.DataFrame(df2)

sns.pairplot(df2)

df2.describe().round(2)

